In [13]:
import numpy as np
import pandas as pd

In [14]:
# create basic sample numpy array
x = np.array([1,2,3,4,5])
print('x =',x)


x = [1 2 3 4 5]


In [15]:
# the shape of an ndarray gives sizes of each dimension
# dtypes refers to the datatypes held in the array
print('x has dimensions: ',x.shape)
print('x is an object of type ',type(x))
print('The elements in x are of type: ',x.dtype)

x has dimensions:  (5,)
x is an object of type  <class 'numpy.ndarray'>
The elements in x are of type:  int64


In [16]:
# ndarrays can also hold strings
x = np.array(['Hello','World'])
print('x =',x)
print('x has dimensions: ',x.shape)
print('x is an object of type ',type(x))
print('The elements in x are of type: ',x.dtype)


x = ['Hello' 'World']
x has dimensions:  (2,)
x is an object of type  <class 'numpy.ndarray'>
The elements in x are of type:  <U5


In [18]:
# type U5 means unicode strings of 5 characters
# numpy arrays must have elements of the same type whereas python lists can have elements of different datatypes
x = np.array([1,2,'World'])
print('x =',x)
print('x has dimensions: ',x.shape)
print('x is an object of type ',type(x))
print('The elements in x are of type: ',x.dtype)

x = ['1' '2' 'World']
x has dimensions:  (3,)
x is an object of type  <class 'numpy.ndarray'>
The elements in x are of type:  <U21


In [21]:
# create a rank 2 ndarray from a nested python list
y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print('y = ',y)
print('Y has dimensions:', y.shape)
print('Y has a total of', y.size, 'elements')
print('Y is an object of type:', type(y))
print('The elements in Y are of type:', y.dtype)

y =  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


In [22]:
# shape retursn (4,3) indicating it is a 2-dimensional array with 4 rows and 3 columns
# creating ndarrays with floats and integers
x = np.array([1,2,3])
y = np.array([1.0,2.0,3.0])
z = np.array([1,2.5,4])

print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int64
The elements in y are of type: float64
The elements in z are of type: float64


In [24]:
# numpy allows you to cast an array as a specific type
# will round floats down to floor of the integer if casting to int
x = np.array([1.5,2.2,3.7,4.0,5.9], dtype=np.int64)
print('x = ',x)
print('The elements in x are of type:', x.dtype)

x =  [1 2 3 4 5]
The elements in x are of type: int64


In [25]:
# saving numpy arrays for later use
x = np.array([1,2,3,4,5])
# save into current working directory
np.save('my_array',x)

In [26]:
# load the saved array
y = np.load('my_array.npy')
print('y = ',y)
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)

y =  [1 2 3 4 5]
y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int64


In [31]:
# generate arrays in a varienty of ways
x = np.zeros((3,4))
y = np.ones((4,3),dtype=int)
z = np.full((2,3),5)
sq = np.eye(5)
diag = np.diag([10,20,30,40,50])
print(x)
print(y)
print(z)
print(sq)
print(diag)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[5 5 5]
 [5 5 5]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


In [34]:
# create arrays with ranges
arange1 = np.arange(10)
print(arange1)
arange2 = np.arange(10,20)
print(arange2)
arange3 = np.arange(1,14,3)
print(arange3)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[ 1  4  7 10 13]


In [36]:
# returns n evenly spaced numbers from start to stop (start, stop, n)
x = np.linspace(0, 25, 10)
print(x)

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [37]:
x = np.linspace(0, 25, 10, endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [38]:
# reshaping arrays
x = np.arange(20)
x = np.reshape(x, (4,5)) # must be able to fit the number of elements evenly
print(x)

# can also chain functions -> np.arange(20).reshape(4,5)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [39]:
# create an array of given shape with random floats between 0,1
x = np.random.random((3,3))
print(x)

[[0.91531346 0.41296468 0.00870011]
 [0.45322385 0.29807854 0.26695402]
 [0.85485706 0.96198183 0.74471095]]


In [40]:
x = np.random.randint(4,15,(2,3))
print(x)

[[ 4 11 11]
 [10  8  4]]


In [42]:
# creates a normally distributed 1000x1000 array with a mean of 0 and std of 0.1
x = np.random.normal(0,0.1,size=(1000,1000))
print(x)

[[-0.1466357   0.08777671  0.00065643 ... -0.09396441  0.16604547
  -0.00712217]
 [-0.0415175   0.03562506 -0.05818826 ... -0.11752209  0.09301531
   0.02878047]
 [-0.14147834  0.23674714  0.15383665 ... -0.04657352  0.00155673
  -0.09949697]
 ...
 [ 0.23240331 -0.0930949   0.00361195 ... -0.08472727  0.08908859
  -0.08689434]
 [-0.08639766 -0.1846168  -0.08263979 ...  0.00289     0.1585614
  -0.01527066]
 [-0.00604127  0.05737188  0.03841799 ...  0.04550251  0.02226173
   0.03758391]]


In [43]:
print('mean: ',x.mean())
print('std: ',x.std())
print('max: ',x.max())
print('min: ',x.min())
print('# pos: ',(x>0).sum())
print('# neg: ',(x<0).sum())

mean:  1.1371840150657328e-05
std:  0.09993192283253433
max:  0.48733939171080637
min:  -0.4819780473430134
# pos:  499793
# neg:  500207


In [49]:
X = np.arange(2,34,2).reshape(4,4)
X

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])